### ISSUE TITLE
Can't enter warp names

### ISSUE THREAD

**Issue by Geekmakes** [XZot1K/HyperDrive#2]
Using on latest paper (1.14.4) and lastest Hyperdrive with EssentialsX and Chat Control. When creating a warp and entering the name of the warp in chat it throws this error: https://pastebin.com/zkzx1mka It doesn't make the warp but typing "cancel" in chat still registers fine. I can still create the warp by commands so guessing this is something chat related?

**Comment by XZot1K** [comment]
The newest update should resolve this issue via priority! HyperDrive has been using ignore cancel and the lowest priority to be more compatible with many plugins, but ChatControl is not a plugin that has been friendly with many of my plugins due to similar usages. This update should resolve the priority issue.

**Comment by Geekmakes** [comment]
Odd, I think the same thing is happening: https://pastebin.com/QztzGVMx I can ask the ChatControl dev if there's a workaround if you need me to.

**Comment by Geekmakes** [comment]
https://pastebin.com/T8ssTKb4 Still having the issue with the latest 5.1.5 jar. It might be a lot of work to incorporate but I've seen anvil gui's used for setting names, that'll bypass any compatibility issues with chat plugins.
Example: https://github.com/WesJD/AnvilGUI

**Comment by XZot1K** [comment]
> 
> 
> https://pastebin.com/T8ssTKb4 Still having the issue with the latest 5.1.5 jar. It might be a lot of work to incorporate but I've seen anvil gui's used for setting names, that'll bypass any compatibility issues with chat plugins.
> Example: https://github.com/WesJD/AnvilGUI

Anvil GUIs are not a bad idea, they were avoided to support 1.7.10 as well, but I will be exploring fixes and possible this now that my vacation is coming to an end!

**Comment by Geekmakes** [comment]
If you need me to, I can test the development build before you upload to Spigot. (geekmakes#5869 on discord)

**Comment by Geekmakes** [comment]
It's working with ChatControl now, just not with my hyperdrive config. Error: https://pastebin.com/adRhbX6x Clueless as to what's causing it, guessing its one of the edited msgs. Heres the config: https://pastebin.com/index.php?e=2 I've edited it a lot so hopefully it's still salvageable.

**Comment by XZot1K** [comment]
> 
> 
> It's working with ChatControl now, just not with my hyperdrive config. Error: https://pastebin.com/adRhbX6x Clueless as to what's causing it, guessing its one of the edited msgs. Heres the config: https://pastebin.com/gN8yZDQv I've edited it a lot so hopefully it's still salvageable.

Sorry for the late reply! Under the filter, section remove all the symbols from the filters! The plugin does this automatically now!

**Comment by XZot1K** [comment]
There will be one adjustment coming to hopefully resolve these chat-based plugin issues, please stay tuned! For now, this issue will be closed. If you encounter a similar issue or something new is revealed please open another issue report!
